version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "translator-aws"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
s3_bucket = "translator-app-bucket"